### ISSUE TITLE
Allowing generated traffic to park on road-side

### ISSUE THREAD

**Issue by abrac** [lcodeca/SUMOActivityGen#14]
Is it possible for SAGA to allow generated traffic to park on the side of the road (as shown in the image below) rather than in designated parking areas? 

I see `activitygen.py` already does it for bicycles, but I'm not sure how to make it do it for all vehicles.

Additionally, it could be useful to trigger this behaviour when parking areas are far from the activity or all parking areas in the rerouter are full.

![park_on_side](https://user-images.githubusercontent.com/55248999/87230949-6a683d00-c3b3-11ea-9190-dcd15797c97d.png)

**Comment by lcodeca** [comment]
It should be possible to trick it by passing an empty list to the parameter "vehicleAllowedParking" from https://github.com/lcodeca/SUMOActivityGen/blob/master/defaults/activitygen.json#L17 because it specifies the vehicles that need to look for a parking area. 
The two possible things that may happen are: 
- it parks closer (like a bicycle) or 
- it disappears (like on-demand).

I'm gonna try it as soon as I can.

**Comment by abrac** [comment]
Thanks for your comment :smiley:! I'll try it tonight and let you know.

**Comment by abrac** [comment]
I can confirm it's working. All vehicles park next to their activities (like bicycles). Thanks again, Lara.

**Comment by lcodeca** [comment]
Good! No problem.
Concerning
>Additionally, it could be useful to trigger this behavior when parking areas are far from the activity or all parking areas in the rerouter are full.

It's not possible because the behavior you want, although a very reasonable one, would require active TraCI rerouting during the simulation, and it cannot be achieved with static input route files.

**Comment by abrac** [comment]
Ah, yes I see. It wouldn't be worth the effort and TraCI would worsen simulation performance.
