### ISSUE TITLE
Traci could not connect in activitygen.py

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#19]
Hi, I have completed 7 steps and obtained the file osm_activitygen.json (input of activitygen.py), but the error occurs as the figure shows:
![error](https://user-images.githubusercontent.com/55737075/94998339-c8d43e80-05e3-11eb-9d96-08c42c45622a.png)
Is Traci unable to connect due to the large road network (it takes about 10 seconds to load with SUMO GUI)？
My sumo version is 1.6.
Thanks in advance.

**Comment by lcodeca** [comment]
Hi, the best I can do is to try to reproduce the problem, and to do so, i need your OSM file and the command line you use. Unfortunately, I don’t have Windows, i use Linux and Mac OSX.

Aside from SAGA, have you tried to use TraCI with another SUMO simulation?
It looks to me a networking error due to Windows, that has nothing o do with SUMO..
Additionally, have checked with the SUMO community?

**Comment by Shiyunyang-seu** [comment]
Thanks for your reply. I have tried to use Traci with other SUMO simulation, and there is no any errors. So, I'm not sure what the actual problem is. Additionally, I checked the SUMO community but do not find the solution. I used to generate the final merged_activity.rou.xml a long time ago and with no errors, whether it is due to the 1.6 version, or whether there are other alternative methods.
Because of the large road network, the input file is too large to upload. Can you leave an E-mail address and I could send the input file to you.Thanks.

**Comment by lcodeca** [comment]
My e-mail address is in the README, lara.codeca@gmail.com
