### ISSUE TITLE
Include demographic data to SAGA

### ISSUE THREAD

**Issue by shift-Jaegger** [lcodeca/SUMOActivityGen#26]
Hi, I want to thank you for your previous response and as soon as I have some ideas on enhacement for bicycles. As I'm working on the usage of the SAGA and as I have previously have used the deprecated ActivityGen, if there are plans on using some of the demographic information such as age, generation of families or residential zones, to enhance the generation of activities after a first cycle of using ScenarioFromOSM and when only using AcivityGen on SAGA for activity generation to better model traffic. Also, what could be the way to go if I want to try and do these enhancements.

Thank you in advance.

**Comment by lcodeca** [comment]
SAGA was never planned to use demographic data. 
You can use those demographic data to make relevant OD matrices for SAGA, with better-defined activity chains.

I'm thinking about adding tags to primary and secondary activities, to match them with tagged buildings/land use extracted from OSM, but it's not working because it requires precise info from OSM, and as you may know, crowdsourced data are not that precise.
