### ISSUE TITLE
The output.summary.xml is unreasonable

### ISSUE THREAD

**Issue by Shiyunyang-seu** [lcodeca/SUMOActivityGen#8]
Hi, I followed the tutorial https://github.com/lcodeca/SUMOActivityGen/blob/master/docs/HOWTO.md. But, I have tried to input different number of trips many times, and the final output curve is similar to the figure below, which is not consistent with the reality. In reality, the traffic flow in the morning and evening peak hours should reach the peak.
![summary](https://user-images.githubusercontent.com/55737075/80603204-ab161280-8a62-11ea-8762-bead02b97129.png)

**Comment by lcodeca** [comment]
The output provided by SUMO counts all the vehicle in the simulation, not only the one that are currently moving in each simulation step. Hence, the graph is consistent with the default SAGA configuration, and does not reflect the peak in moving people/vehicles because it counts the parked cars and waiting people.

**Comment by lcodeca** [comment]
See
- https://github.com/eclipse/sumo/issues/6964
- https://github.com/eclipse/sumo/issues/6966
for further details.
